/*

                                    ,▄█▄                 
    ]█▄▄                         ╓█████▌                 
    ▐██████▄                   ▄█████▓╣█                 
     ║████████▄,  ,  ,,▄,▄▄▄▓██████╬╬╣╣▌                 
      ╚███╣██████████▓▓▓▓██████████╩╠╬▓                  
       ╙█╬╬╬▓███████████████████████▒▓▌                  
        ╙▓█▓██████████████████████████                   
         ╚██████▀███████████╩█▓▌▐▓████▄                  
         '║█████`╣█Γ║████████▄▄φ▓█████▌                 
          ║█████████████████████▓█████▌                  
           █████████████▓▓████████████                   
           ║█████████████████████████                    
          ]█████████████████████████                     
         ,▓██████████████████████████                    
        ▓█████████████████████████████µ                  
       ▐███████████████████████████████▄▄                
       ║█████████████████████████████████╬╬╣▓            
   ,╔╦║███████████████████████████████████▓╬╬╣           
,≥≥⌠░░░╠▓████████████████████████████████████▓▓          
,;=-',▄█████████████████████████████████████████▓        
                                                         
                                                         
                                                         
  ██████╗ ███████╗██╗   ██╗ ██████╗██╗  ██╗██╗ ██████╗   
  ██╔══██╗██╔════╝╚██╗ ██╔╝██╔════╝██║  ██║██║██╔════╝   
  ██████╔╝███████╗ ╚████╔╝ ██║     ███████║██║██║        
  ██╔═══╝ ╚════██║  ╚██╔╝  ██║     ██╔══██║██║██║        
  ██║     ███████║   ██║   ╚██████╗██║  ██║██║╚██████╗   
  ╚═╝     ╚══════╝   ╚═╝    ╚═════╝╚═╝  ╚═╝╚═╝ ╚═════╝   
                                                         
                                                         

This file was automatically generated by my cat, Aster.
He does not want you mucking about with his files,
and we are pretty lax on trimming his nails.

I mean, we have him pretty well fenced in but he is an
escape artist and he still manages to get fleas!

My point is, don't go mucking about with his files!

He actually has a hopefully well-tempered message for
us humans, he says:

"
  Dear pathetic humans,

  Here is a haiku to keep you in line

  don't dare go mucking
  with my files, I lyke them fine
  prettierignore
"

*/

import {
  type CalendarDate,
  type DateTime,
  type ClockTime,
  type ClockTimeTz,
} from '@rvoh/dream'
/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */
import type { ColumnType } from 'kysely'

export type ApplianceTypesEnum = 'dishwasher' | 'microwave' | 'oven' | 'stove'

export const ApplianceTypesEnumValues = [
  'dishwasher',
  'microwave',
  'oven',
  'stove',
] as const

export type ArrayType<T> =
  ArrayTypeImpl<T> extends (infer U)[] ? U[] : ArrayTypeImpl<T>

export type ArrayTypeImpl<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S[], I[], U[]>
    : T[]

export type BathOrShowerStylesEnum =
  | 'bath'
  | 'bath_and_shower'
  | 'none'
  | 'shower'

export const BathOrShowerStylesEnumValues = [
  'bath',
  'bath_and_shower',
  'none',
  'shower',
] as const

export type BedTypesEnum =
  | 'bunk'
  | 'cot'
  | 'king'
  | 'queen'
  | 'sofabed'
  | 'twin'

export const BedTypesEnumValues = [
  'bunk',
  'cot',
  'king',
  'queen',
  'sofabed',
  'twin',
] as const

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>

export type LocalesEnum = 'en-US' | 'es-ES'

export const LocalesEnumValues = ['en-US', 'es-ES'] as const

export type LocalizedTypesEnum = 'Host' | 'Place' | 'Room'

export const LocalizedTypesEnumValues = ['Host', 'Place', 'Room'] as const

export type PlaceStylesEnum =
  | 'cabin'
  | 'cave'
  | 'cottage'
  | 'dump'
  | 'lean_to'
  | 'tent'
  | 'treehouse'

export const PlaceStylesEnumValues = [
  'cabin',
  'cave',
  'cottage',
  'dump',
  'lean_to',
  'tent',
  'treehouse',
] as const

export type RoomTypesEnum =
  | 'Bathroom'
  | 'Bedroom'
  | 'Den'
  | 'Kitchen'
  | 'LivingRoom'

export const RoomTypesEnumValues = [
  'Bathroom',
  'Bedroom',
  'Den',
  'Kitchen',
  'LivingRoom',
] as const

export type Timestamp = ColumnType<DateTime | CalendarDate>

export interface AuthAccounts {
  accessToken: string | null
  accessTokenExpiresAt: Timestamp | null
  accountId: string
  createdAt: Timestamp
  id: Generated<string>
  idToken: string | null
  password: string | null
  providerId: string
  refreshToken: string | null
  refreshTokenExpiresAt: Timestamp | null
  scope: string | null
  updatedAt: Timestamp
  userId: string
}

export interface AuthSessions {
  createdAt: Timestamp
  expiresAt: Timestamp
  id: Generated<string>
  ipAddress: string | null
  token: string
  updatedAt: Timestamp
  userAgent: string | null
  userId: string
}

export interface AuthVerifications {
  createdAt: Timestamp
  expiresAt: Timestamp
  id: Generated<string>
  identifier: string
  updatedAt: Timestamp
  value: string
}

export interface Bookings {
  createdAt: Timestamp
  deletedAt: Timestamp | null
  endsOn: Timestamp
  guestId: string
  id: Generated<string>
  placeId: string
  startsOn: Timestamp
  updatedAt: Timestamp
}

export interface Guests {
  createdAt: Timestamp
  deletedAt: Timestamp | null
  id: Generated<string>
  updatedAt: Timestamp
  userId: string
}

export interface HostPlaces {
  createdAt: Timestamp
  deletedAt: Timestamp | null
  hostId: string
  id: Generated<string>
  placeId: string
  updatedAt: Timestamp
}

export interface Hosts {
  createdAt: Timestamp
  deletedAt: Timestamp | null
  id: Generated<string>
  updatedAt: Timestamp
  userId: string
}

export interface LocalizedTexts {
  createdAt: Timestamp
  deletedAt: Timestamp | null
  id: Generated<string>
  locale: LocalesEnum
  localizableId: string
  localizableType: LocalizedTypesEnum
  markdown: string | null
  title: string | null
  updatedAt: Timestamp
}

export interface Places {
  createdAt: Timestamp
  deletedAt: Timestamp | null
  id: Generated<string>
  name: string
  sleeps: number
  style: PlaceStylesEnum
  updatedAt: Timestamp
}

export interface Reviews {
  body: string
  bookingId: string
  createdAt: Timestamp
  deletedAt: Timestamp | null
  guestId: string
  id: Generated<string>
  placeId: string
  rating: number
  updatedAt: Timestamp
}

export interface Rooms {
  appliances: Generated<ArrayType<ApplianceTypesEnum>>
  bathOrShowerStyle: BathOrShowerStylesEnum | null
  bedTypes: Generated<ArrayType<BedTypesEnum>>
  createdAt: Timestamp
  deletedAt: Timestamp | null
  id: Generated<string>
  placeId: string
  position: number | null
  type: RoomTypesEnum
  updatedAt: Timestamp
}

export interface Users {
  createdAt: Timestamp
  deletedAt: Timestamp | null
  email: string
  emailVerified: Generated<boolean>
  encryptedPhone: string | null
  id: Generated<string>
  image: string | null
  name: Generated<string>
  updatedAt: Timestamp
}

export interface DB {
  auth_accounts: AuthAccounts
  auth_sessions: AuthSessions
  auth_verifications: AuthVerifications
  bookings: Bookings
  guests: Guests
  host_places: HostPlaces
  hosts: Hosts
  localized_texts: LocalizedTexts
  places: Places
  reviews: Reviews
  rooms: Rooms
  users: Users
}

export class DBClass {
  auth_accounts: AuthAccounts
  auth_sessions: AuthSessions
  auth_verifications: AuthVerifications
  bookings: Bookings
  guests: Guests
  host_places: HostPlaces
  hosts: Hosts
  localized_texts: LocalizedTexts
  places: Places
  reviews: Reviews
  rooms: Rooms
  users: Users
}
